
spring:
  application:
    name: mongoTest
  data:
    mongodb:
      uri: mongodb://39.107.234.182:27017
      database: mongoTest
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 9001

